.\"
.\" Copyright 2015 Alexandre Moghrabi (alexandre.moghrabi@epitech.eu)
.\"
.\" @(#)got.6
.\"
.TH GOT 6 "June 19, 2015"
.SH NAME
got \- Display quotes from Game Of Thrones
.SH SYNOPSIS
.B got
[OPTIONS] [\-c \fICHARACTER\fP]
.SH DESCRIPTION
.B got
is used to write GoT quotes on the console. Very usefull.
.SH OPTIONS
.l
.B got
accepts the following options:
.TP 8
.B \-v
 Show the version info.
.TP 8
.B \-c
 Get a random quote from \fICHARACTER\fP
.TP 8
.B \-h
 Show the help.
.SH COPYRIGHT
got command Copyright \(co 2015 by Alexandre Moghrabi <alexandre.moghrabi@epitech.eu>
.PP
This program is under the MIT license.
.SH AUTHOR
This manpage is written by Alexandre Moghrabi (alexandre.moghrabi@epitech.eu)
