.\"
.\" Copyright 2015 Alexandre Moghrabi (alexandre.moghrabi@epitech.eu)
.\"
.\" @(#)got.1
.\"
.TH GOT 1 "June 19, 2015"
.SH NAME
got \- Display quotes from Game Of Thrones
.SH SYNOPSIS
.B got
.SH DESCRIPTION
.B got
is used to write GoT quotes on the console. Very usefull.
.SH AUTHOR
Alexandre Moghrabi (alexandre.moghrabi@epitech.eu)
